### PR TITLE
Fix for when next query occurence happens on the excerpt border

### PR DESCRIPTION
**Pull request by graker**
Hello

It seems that I found another issue with marked search query occurrences happen on the excerpt border. Specifically, if you have your first match found and it is safe inside the excerpt, you can still have the second (or third) one appearing right on the end of excerpt. Previous issue was when opening mark tag was in the excerpt and closing one wasn't. This one is a bit trickier: it happens when we have a partial tag on the excerpt end, like this:
`... some text ... <ma...`

Although this one is rare, it still happens now and then and mess the markup. This PR is for fixing the issue by saving positions of all query matches in text and then going over them until we find one on the excerpt border (or until we go outside of the excerpt). If such a match is found, the excerpt length will be reduced to leave this match outside of it.

`adjustExcerptLength()` method is a bit cluttered with if/elses, sorry for that. Couldn't think of a way to make it prettier given that we have two different situations with starting position of the excerpt.

### CODE REVIEW

**Comment by tobias-kuendig** [comment]
Do you have an example query and content where this problem occurs? I'm having a hard time reproducing it.

**Comment by graker** [comment]
Check out this page: https://graker.ru/search?q=%D0%B3%D0%BE%D1%80%D0%BE%D0%B4
I temporarily disabled this fix on my site to reproduce the bug. If you look into page markup near the break (it's where all results are inside one container instead of separate ones), you'd find an unclosed and weird `<m...` tag - that's because `<mark>город</mark>` string occurred right on the excerpt border.

**Comment by tobias-kuendig** [comment]
Allright, thanks! I'll look into it.

Graker <notifications@github.com> schrieb am So., 12. März 2017, 17:05:

Check out this page:
https://graker.ru/search?q=%D0%B3%D0%BE%D1%80%D0%BE%D0%B4
I temporarily disabled this fix on my site to reproduce the bug. If you
look into page markup near the break (it's where all results are inside one
container instead of separate ones), you'd find an unclosed and weird <m...
tag - that's because <mark>город</mark> string occurred right on the
excerpt border.

—
You are receiving this because you commented.


Reply to this email directly, view it on GitHub
<https://github.com/OFFLINE-GmbH/oc-site-search-plugin/pull/31#issuecomment-285954273>,
or mute the thread

**Comment by graker** [comment]
No problem, just tell me please when you finished with the page so I'd enable the fix back again :)

**Comment by tobias-kuendig** [comment]
You can enable it again so your page is working, thanks.

Graker <notifications@github.com> schrieb am So., 12. März 2017, 17:24:

**Comment by tobias-kuendig** [comment]
I'm trying out another solution: Simply wrap the query _after_ the excerpt has been generated.

Would you mind testing the fix and see if it solves your problem case?
https://github.com/OFFLINE-GmbH/oc-site-search-plugin/commit/e09d7360582356076ed338e3d48b9bf5e3ca0e71

I have published a new version of the plugin as an edge update.

**Comment by graker** [comment]
I think, to wrap it after the excerpt is a much better solution. I'll try it later this week, thank you.

**Comment by graker** [comment]
Hi @tobias-kuendig, I tried the latest develop branch and my case is solved in it. So this PR is not relevant any more :) Thank you, your approach is much better.

**Comment by tobias-kuendig** [comment]
Thanks for testing! Released as 1.2.25.

**Pull request closed without merging**
