### PR TITLE
Add French translation

### PR DESCRIPTION
**Pull request by damsfx**

### CODE REVIEW

**Comment by tobias-kuendig** [comment]
It looks like this PR only contains english strings, did you forget to commit something?

**Comment by damsfx** [comment]
> 
> 
> It looks like this PR only contains english strings, did you forget to commit something?

Yes, unfortunately !! 
I'm so confused.

What do you want me to do ... create a new push request ??

**Comment by tobias-kuendig** [comment]
:grin: no worries! You can just commit it on the same branch so it is added to this PR. Or create a new PR, whatever works best for you.

**Comment by damsfx** [comment]
Done, I'm sorry, ...  
I made changes to the mall plugin at the same time, I got lost in the pull requests.

**Comment by tobias-kuendig** [comment]
Perfect, thank you!

**Pull request merged**
